// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABrZxcKAe3Iq-7Pd6V8vkLmLpKby0Ue6c',
    appId: '1:750042662104:web:dce7c31342eca77d6303ad',
    messagingSenderId: '750042662104',
    projectId: 'quiz-duel-1b09b',
    authDomain: 'quiz-duel-1b09b.firebaseapp.com',
    storageBucket: 'quiz-duel-1b09b.firebasestorage.app',
    measurementId: 'G-31FX59D48N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0T4nM3f4aRlYLJk0zGtWPruyJDBRLO00',
    appId: '1:750042662104:android:bb07452e98dbcb166303ad',
    messagingSenderId: '750042662104',
    projectId: 'quiz-duel-1b09b',
    storageBucket: 'quiz-duel-1b09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKv1hwUyJCRKwuOinE7T9uLTILUFG0OHY',
    appId: '1:750042662104:ios:e419e48401b837216303ad',
    messagingSenderId: '750042662104',
    projectId: 'quiz-duel-1b09b',
    storageBucket: 'quiz-duel-1b09b.firebasestorage.app',
    iosBundleId: 'com.example.quizgame',
  );
}
